<?php

namespace Makm\Tasks\Actions;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-16 at 18:35:26.
 */
class ActionFunctionTest extends TestCase
{

    /**
     * @var ActionFunction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ActionFunction;

        $bla2 = '2';
        $this->object->setFunction(function ($bla) use ($bla2)
        {
            echo "Say hello, {$bla}+{$bla2}";
        });
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Makm\Tasks\Actions\ActionFunction::getBodyOfFunction
     */
    public function testGetBodyOfFunction()
    {
        $method = new \ReflectionMethod(
                \get_class($this->object), 'getBodyOfFunction'
        );
        $method->setAccessible(TRUE);
        $result = $method->invoke($this->object);
        $this->assertInternalType('array', $result);
    }

    /**
     * @covers Makm\Tasks\Actions\ActionFunction::setFunction
     */
    public function testSetFunction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
